// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7jxwPqP_9gNUpcWQtoxWESxuERb34E8',
    appId: '1:1095655060258:web:745509f0e983c4c57dab7b',
    messagingSenderId: '1095655060258',
    projectId: 'colorvelvetus',
    authDomain: 'colorvelvetus.firebaseapp.com',
    storageBucket: 'colorvelvetus.appspot.com',
    measurementId: 'G-KH35B2NB6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdFrIMspevo_klqCU_fc2g1JW_VqYKfNI',
    appId: '1:1095655060258:android:f802692d0a7e0d877dab7b',
    messagingSenderId: '1095655060258',
    projectId: 'colorvelvetus',
    storageBucket: 'colorvelvetus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf80o4IQLhm3aB0iidoJZ3WwxOXkH1ros',
    appId: '1:1095655060258:ios:734d9bb722d776e37dab7b',
    messagingSenderId: '1095655060258',
    projectId: 'colorvelvetus',
    storageBucket: 'colorvelvetus.appspot.com',
    iosClientId: '1095655060258-r745v1h5hktnvgbpe1olj15i2q8al508.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorvelvetusus',
  );
}
